logging.level:
  ru.yandex.practicum.filmorate: DEBUG
spring:
  sql.init:
    mode: ALWAYS
    platform: h2
    schema-locations: classpath:schema.sql
  datasource:
    url: jdbc:h2:file:./db/filmorate;DATABASE_TO_UPPER=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
